openapi: "3.0.0"
info:
  version: 1.0.0
  title: Clean Architecture Example
servers:
  - url: http://localhost:8080
paths:
  /:
    get:
      summary: Health Check
      operationId: healthCheck
      tags:
        - health
      responses:
        '200':
          description: Return if the health check is success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Health"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /login:
    post:
      summary: Authenticate
      operationId: login
      tags:
        - auth
      requestBody:
        description: |
          This endpoint helps for authentication users, it uses a `json` body with the arguments `username` and `password`, it returns a `token` that is going to be used to identify the user.
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Credentials'
      responses:
        '200':
          description: Return authentication token
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Token"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /pets/{petId}:
    get:
      summary: Info for a specific pet
      operationId: showPetById
      tags:
        - pets
      parameters:
        - name: petId
          in: path
          required: true
          description: The id of the pet to retrieve
          schema:
            type: string
      responses:
        '200':
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Pet"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    Health:
      type: object
      required:
        - success
      properties:
        success:
          type: boolean
    Credentials:
      type: object
      required:
        - username
        - password
      properties:
        username:
          type: string
        password:
          type: string
    Token:
      type: object
      required:
        - token
      properties:
        token:
          type: string
    Pet:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        tag:
          type: string
    Pets:
      type: array
      maxItems: 100
      items:
        $ref: "#/components/schemas/Pet"
    Error:
      type: object
      required:
        - error
      properties:
        error:
          type: string